Add avatar and name to post
Dharmik48/seeit pull request #19
Opened 2022-08-03 21:45 UTC by swhemi

I have worked accordingly to the contributing guide and added the user avatar and name to the post. I tried a few different ways that's why there are so many new posts. Sorry about that and thanks for letting me work on this issue.

2022-08-04 12:01 UTC, Dharmik48 requested changes
Good job @swhemi! The code looks good!

I only have one suggestion, on smaller screens, the avatar isn't a proper circle and the font size is also very big. 

So can you fix these two issues so we can merge the PR?

2022-08-04 23:59 UTC, swhemi commented
Hey, yeah sure, I will change that! Sorry, didn't check on that properly.

2022-08-05 00:49 UTC, swhemi commented
Hey @Dharmik48, I just changed the user avatar and name size. Is it okay this way or should it be smaller/bigger (if it's too small now)?

2022-08-05 08:43 UTC, Dharmik48 requested changes
This looks better but can you implement it with Tailwind CSS and not vanilla CSS?

2022-08-05 14:01 UTC, swhemi commented
Hey @Dharmik48, I just changed it into Tailwind CSS. First time working with Tailwind, hope it looks fine.

2022-08-05 14:11 UTC, mdazad1508 commented
looks good @swhemi

2022-08-05 16:11 UTC, Dharmik48 requested changes
Awesome work🎉

Looks way better! One last suggestion, even when there is so much available space, the username is getting wrapped to a new line.

![image](https://user-images.githubusercontent.com/64529217/183117906-884387da-6b6e-4e34-bbfd-2676a2e1fc1b.png)

Just fix that and it will be good to merge🚀

2022-08-06 10:53 UTC, Dharmik48 approved these changes
LGTM🚀

Great work @swhemi! This looks great!

Lets get it merged🎉 Thanks a lot for contributing🚀

2022-08-06 10:54 UTC, merged

2022-08-12 22:52 UTC, swhemi commented
Thank you for letting me work on this issue! :)

2022-08-13 06:42 UTC, Dharmik48 commented
> Thank you for letting me work on this issue! :)

It was good to have you as a conributor😊